steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - echo "$(git diff --name-only HEAD...main)"
  - |
    if git diff --name-only HEAD | grep -q "us/"; then
      echo "The file HAS changed"
      python app/app.py
    else
      echo "No, the file did not change, we shall exit"
      exit 0
    fi