steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - echo "$(git log)"
  - echo "$(git show --name-only master)"
  - echo "$(git show --name-only --format= $COMMIT_SHA)"
  - |
    if git diff --name-only HEAD~1 | grep -q "us/"; then
      echo "The file HAS changed"
      python app/app.py
    else
      echo "No, the file did not change, we shall exit"
      exit 0
    fi