steps:
- name: python
  entrypoint: 'bash'
  dir: app
  args: 
  - '-c'
  - git checkout master
  - |
    echo "$(git remote -v)"
    echo "$(git show --name-only $COMMIT_SHA)"
    if git show --name-only $COMMIT_SHA | grep -q "us/"; then
      echo "The file HAS changed"
      python us/simple_app.py
    else
      echo "No, the file did not change, we shall exit"
      exit 0
    fi



