steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - $(git checkout master)
  - |
    if git diff --name-only HEAD~2 -- us/; then
      echo "The file HAS changed"
      python app/app.py
    else
      echo "No, the file did not change, we shall exit"
      exit 0
    fi